Add config + options to teleport
skyscrapers/docker-images pull request #10
Opened 2017-12-21 15:38 UTC by MattiasGees

2017-12-21 17:15 UTC, iuriaranda approved these changes

2017-12-22 08:11 UTC, ringods requested changes

2017-12-22 08:11 UTC, ringods commented on teleport/entrypoint.sh
> +if [ -z "${CLUSTER_NAME}" -a "${ENABLE_AUTH}" == "yes" ]; then
Shellcheck.net: https://github.com/koalaman/shellcheck/wiki/SC2166

2017-12-22 08:11 UTC, ringods commented on teleport/entrypoint.sh
> +envsubst < "/etc/teleport.yaml" > "/etc/teleport.yaml"
Shellcheck.net: https://github.com/koalaman/shellcheck/wiki/SC2094

2017-12-22 08:49 UTC, ringods approved these changes

2017-12-22 08:50 UTC, merged